# site settings
title: Ömer
subtitle: Akincir
email: personal.omer.akincir@gmail.com
description: Kendini bilişim sektörüne adamış tutkulu bir sızma testi uzmanıyım.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: wasp

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

socials:
  GitHub: https://github.com/waspthebughunter
  LinkedIn: https://www.linkedin.com/in/omerakincir

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 


